### ISSUE TITLE
creation of "Sequomics Corporation" logo in SVG format by using adobe illustrator CS6. 

### ISSUE THREAD

**Issue by sequomics** [sequomics/home#1]
A SVG logo have to create by using adobe illustrator CS6.

Requirement:
- svg format without background,
- it's must also be in PNG format without background,
- illustrator and respective psd, layer by layer must be provided and completion of final one,
- all should be in .zip format have to provide.

**Comment by sequomics** [comment]
Concept:
[A]. to design a logo:
- "S" of Sequomics in a middle of two circles i.e., both in different color and after that "S" inside in a different color. So, it will be a hallmark of the company.
- It will be appear nice with may be with emboss or engraved effects.

View:
- Two circles represent the merger of two disciples, i.e., IT and Mathematics/or business and "S" in middle that reflects "what we are doing?".

**Comment by sequomics** [comment]
Update:
Labyrinth effects should be added.

**Comment by marianelagrande** [comment]
Hi.  Today I can't continue  with the logo.  But please tell me what do you
want to do and maybe tomorrow I  will do.
Cheers

**Comment by sequomics** [comment]
Logo is completed.
